# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1df5bd4673e7bd55fdd516237d0f44f7d79515eb1ae1aebd0858c5fbe3b705daf3b03d5017f0a711837beead93fce7d759cc33c5be0d54b28ebb6398a8d7445d

test:
  secret_key_base: aeaa655925c3f20234ca4a4bbc76f61e70976fd3556e0b205a1907996af7c46a547b22e59024333ce5105481b0e416cfedb290ea7e72cd11506320edeb4e1b96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
